#!/bin/bash

# A pytest wrapper that rebuilds scripts before executing tests.

# From https://stackoverflow.com/a/4774063
REPO_DIR="$( cd -- "$(dirname "$0")/.." >/dev/null 2>&1 ; pwd -P )"

cd "$REPO_DIR"
make all
pytest $@
